!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  enable: true
  equal: true
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        dictitems:
          Cutting: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 2
              name: Cutting
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
              x_enable: true
              x_max: 5000.0
              x_min: 100.0
              y_enable: true
              y_max: 4000.0
              y_min: 1170.0
              z_enable: true
              z_max: 1600.0
              z_min: 750.0
            state: []
          Plane_Detection: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 4
              max_it: 500
              method: 0
              n_planes: 2
              name: Plane_Detection
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              th_dist: 20.0
              type: ''
            state: []
          Subsampling: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              enable: true
              equal: true
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 1
              name: Subsampling
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
              x: 30.0
              y: 10.0
              z: 10.0
            state: []
          Transformation: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 3
              name: Transformation
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              rx: 2.0
              ry: -1.9
              rz: 0.0
              state: true
              tx: 10.0
              ty: 70.0
              type: ''
              tz: -95.0
            state: []
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
    state: []
  max_it: 500
  method: 0
  n_planes: 2
  rx: 2.0
  ry: -1.9
  rz: 0.0
  th_dist: 20.0
  tx: 10.0
  ty: 70.0
  tz: -95.0
  x: 30.0
  x_enable: true
  x_max: 5000.0
  x_min: 100.0
  y: 10.0
  y_enable: true
  y_max: 4000.0
  y_min: 1170.0
  z: 10.0
  z_enable: true
  z_max: 1600.0
  z_min: 750.0
state: []
