calib:
  cam1_cam2:
    matching:
      iss_nms_radius: 25.0
      iss_support_radius: 25.0
      kp_dupl_rej: true
      kp_est_radius: 50.0
      match_th: 10.0
      match_th_dist: 100.0
      normal_radius: 50.0
      x_enable: true
      x_min: -265.0
      x_max: 5000.0
      y_enable: false
      y_min: -505.0
      y_max: 395.0
      z_enable: true
      z_min: 30.0
      z_max: 800.0
    transform_estimation:
      frame: cam_center
      use_points: true
      use_planes: true
      compute_rotation: true
      compute_translation: true
      project_points: true
      inverse: false
      planes_weight: 1.0
    merging:
      frame: cam_center
      enable_cutting: true
      y_pose: 40.0
      width: 720.0
    tf:
      cam1_cam2:
        freq: 10
        rot_filter_type: 2
        rot_filter_weight: 2.0
        transl_filter_type: 2
        transl_filter_weight: 2.0