calib:
  cam1_cam2:
    matching:
      iss_nms_radius: 15.0
      iss_support_radius: 15.0
      kp_dupl_rej: true
      kp_est_radius: 20.0
      match_th: 0.5
      match_th_dist: 100.0
      normal_radius: 50.0
      x_enable: true
      x_max: 5000.0
      x_min: 480.0
      y_enable: false
      y_max: 1700.0
      y_min: 800.0
      z_enable: true
      z_max: 1300.0
      z_min: 830.0