calib:
  cam1:
    cloud:
      tx: -12.0
      ty: 30.0
      tz: -40.0
      rx: 3.0
      ry: -1.9
      rz: 0.0
    preproc:
      y_enable: true
      y_min: 170.0
      y_max: 2700.0
  cam2:
    cloud:
      tx: 0.0
      ty: 0.0
      tz: -10.0
      rx: -0.3
      ry: -1.0
      rz: 0.0
    preproc:
      y_min: 0.0
      y_max: 2470.0
  scene:
    cloud:
      tx: 0.0
      ty: 0.0
      tz: 0.0
      rx: 0.0
      ry: 0.0
      rz: 0.0
    preproc:
      y_enable: true
      y_min: -100.0
      y_max: 2800.0
      z_enable: true
      z_min: 720.0
      z_max: 2000.0
  # match:
  #   x_enable: true
  #   x_min: 450.0
  #   x_max: 1500.0
  #   y_enable: true
  #   y_min: 900.0
  #   y_max: 1900.0
  #   z_enable: true
  #   z_min: 900.0
  #   z_max: 1050.0