!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        dictitems:
          Cutting: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 4
              name: Cutting
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
              x_enable: true
              x_max: 1500.0
              x_min: 450.0
              y_enable: true
              y_max: 1900.0
              y_min: 900.0
              z_enable: true
              z_max: 1050.0
              z_min: 900.0
            state: []
          Feature_computation: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 3
              kp_dupl_rej: true
              kp_est_radius: 30.0
              match_th: 12000.0
              name: Feature_computation
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
            state: []
          Keypoints_extraction: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 2
              iss_nms_radius: 10.0
              iss_support_radius: 10.0
              name: Keypoints_extraction
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
            state: []
          Plane_matching: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 1
              name: Plane_matching
              normal_radius: 5.0
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              plane_matching: false
              state: true
              type: ''
            state: []
          Transform_estimation: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 5
              name: Transform_estimation
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              planes_weight: 1.0
              state: true
              type: ''
              use_planes: true
              use_points: true
            state: []
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
    state: []
  iss_nms_radius: 10.0
  iss_support_radius: 10.0
  kp_dupl_rej: true
  kp_est_radius: 30.0
  match_th: 12000.0
  normal_radius: 5.0
  plane_matching: false
  planes_weight: 1.0
  use_planes: true
  use_points: true
  x_enable: true
  x_max: 1500.0
  x_min: 450.0
  y_enable: true
  y_max: 1900.0
  y_min: 900.0
  z_enable: true
  z_max: 1050.0
  z_min: 900.0
state: []
