calib:
  cam1:
    planes:
      enable: true
      subsize: 40.0
      n_planes: 2
      th_dist: 50.0
  cam2:
    planes:
      enable: true
      subsize: 40.0
      n_planes: 2
      th_dist: 50.0
  final:
    planes:
      enable: true
      subsize: 40.0
      n_planes: 2
      th_dist: 50.0